name: she_if_life
description: SheIfLife - Windows-first retail expiry tracking app
publish_to: 'none' # 本地开发阶段，不发布到 pub.dev

version: 0.1.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # ===== 必需依赖 =====
  pdf: ^3.11.0
  path_provider: ^2.1.4
  file_picker: ^8.0.0

  # ===== 拍照 & 扫码 =====
  image_picker: ^1.0.7
  mobile_scanner: ^5.2.3

  # （后续可加）
  # intl: ^0.19.0
  # uuid: ^4.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
